avocado-framework/aexpect

aexpect.spec, aexpect/client.py, aexpect/shared.py, setup.py
=> Misc fixes 09-17-2015

requirements-travis.txt
Signed-off-by: Lucas Meneghel Rodrigues <lmr@scylladb.com>
=> requirements-travis.txt: Update the inspektor version being used

aexpect/client.py
1. Add param "safe" when execute cmd, default is False.
In serial sessions, frequently the kernel might print debug or
error messages that make read_up_to_prompt to timeout. Let's try
to be a little more robust and send a carriage return, to see if
we can get to the prompt when safe=True.
Signed-off-by: Cong Li <coli@redhat.com>
=> aexpect/client.py: Add safe mode when execute cmd.

Makefile, requirements-travis.txt
=> requirements: Use the latest inspektor in travis

aexpect/client.py
It's near-impossible to get the correct encoding of the underlying
program as one can execute remote connections or shells with different
environment by aexpect. Let's use PYTHONENCODING or "utf-8" by default
while allowing the user to switch it by changing instance.encoding
variable.
=> aexpect.client: Get encoding or use utf-8 by default

Makefile, aexpect.spec, setup.py
Signed-off-by: Lucas Meneghel Rodrigues <lookkas@gmail.com>
=> aexpect: Bump version to 1.3.0

aexpect/client.py
=> aexpect/client.py: minor typo fix

Makefile, aexpect/__init__.py, aexpect/client.py, aexpect/exceptions.py, aexpect/shared.py, aexpect/utils/astring.py, aexpect/utils/data_factory.py, aexpect/utils/genio.py, aexpect/utils/path.py, aexpect/utils/process.py, aexpect/utils/wait.py, python-aexpect.spec, scripts/aexpect-helper, scripts/aexpect_helper, setup.py, tests/test_client.py, tests/test_pass_fds.py
OK, we want to cleanup Avocado, let's start with a smaller project first. There are some probably controversial commits so I'm open to cherry-picking and hammering out the details in following PRs.
=> Enable most checks in pylint

aexpect/client.py
As the subject implies, this aims to enable with statement for 'Spawn'
and its descendant classes.
Signed-off-by: lolyu <lolyu@redhat.com>
=> support with statement

aexpect/client.py, aexpect/utils/process.py
=> pylint fixes

scripts/aexpect_helper
Signed-off-by: Plamen Dimitrov <pdimitrov@pevogam.com>
=> Resolve any alerts generated by LGTM

.travis.yml
Update and extend python 3 support for the entire repo
=> Python3 support

.travis.yml, Makefile, aexpect/client.py, aexpect/remote_door.py, aexpect/utils/path.py, python-aexpect.spec, setup.py
Cleanups and CI fixes in preparation for release 1.6.0
---
Changes from v1 (#63):
* Removed `subprocess` conditional import relevant to Python 2 only (@luckyh)
=> Preparations for release 1.6.0 [v2]

Makefile, aexpect/client.py, aexpect/exceptions.py, aexpect/remote.py, aexpect/remote_door.py, aexpect/rss_client.py, aexpect/utils/astring.py, aexpect/utils/path.py, aexpect/utils/process.py
Signed-off-by: Plamen Dimitrov <pdimitrov@pevogam.com>
=> Remove pre-release pylint issues

aexpect/remote_door.py, tests/test_remote_door.py
Extension of the remote door to remove Windows machines,
added support for indented functions, output returning remote
function calls, auto-imported deserializable exceptions.
=> Remote door improvements

aexpect/remote.py
1) Make 'PreferredAuthentications' and UserKnownHostsFile changeable.
2) VMware vCenter login support
Signed-off-by: Xiaodai Wang <xiaodwan@redhat.com>
=> Make two ssh options changeable and support VMware Vcenter login

Makefile
=> Makefile: add a pypi target to ease future releases

aexpect/client.py, aexpect/utils/genio.py
Some fixes related to newer pylint version
=> Travis fixes

aexpect/client.py, aexpect/exceptions.py, aexpect/remote.py, aexpect/remote_door.py, aexpect/rss_client.py, aexpect/shared.py, aexpect/utils/astring.py, aexpect/utils/data_factory.py, aexpect/utils/genio.py, aexpect/utils/path.py, aexpect/utils/process.py, scripts/aexpect_helper, setup.py, tests/test_client.py, tests/test_pass_fds.py, tests/test_remote_door.py
Addressing the newly added C0209 and W1514 checks failures.
=> Pylint style fixes

aexpect/rss_client.py
Issue:https://github.com/avocado-framework/aexpect/issues/94
Signed-off-by: Yanan Fu <yfu@redhat.com>
=> rss_client: fix syntax error

aexpect/client.py, tests/test_client.py
The commit fixes the bug listed below. It also fixes a file leak that was being reported when users were opening and closing sessions while keeping a reference to them even if they were closed.
The commit introduces the needed changes to make sure the file leak is fixed.
ID: 2003990
=> client: Make sure aexpect_helper file descriptors are closed

aexpect/rss_client.py, setup.py
=> Remove six dependency

.gitignore, Makefile, aexpect/client.py, aexpect/ops.py, aexpect/remote.py, aexpect/remote_door.py, aexpect/rss_client.py, aexpect/shared.py, aexpect/utils/astring.py, aexpect/utils/genio.py, aexpect/utils/path.py, aexpect/utils/process.py, aexpect/utils/wait.py, python-aexpect.spec, tests/test_client.py, tests/test_remote_door.py
Fix a few issues I found while setting up my new laptop.
=> Small Fixes

aexpect/ops.py
As most calls would check for nonzero exit status and strip the command output let's reuse the same logic as much as we can.
=> Implement a reusable subcommand output and status processing routine

Makefile, aexpect/ops_linux.py, aexpect/ops_windows.py
=> Add a generic ops module for windows platforms
