aexpect/client.py, aexpect/shared.py
These are simple Python 3 syntax changes that adds compatibility
(as far as I exercised it) to aexpect.
=> Py3K syntax fixes

Makefile
The setuptools which replaced the distutils in
0f405f8d757a55abf82af24d9b7141e96469e9cd does not support the `--prune`
argument, making it impossible to build packages. Let's adjust the
Makefile.
=> Makefile: Remove the unsupported --prune argument

aexpect/client.py, aexpect/utils/data_factory.py, aexpect/utils/process.py, setup.py
This extends the initial python3 support from https://github.com/autotest/aexpect/pull/7. Not every functionality was tested on python3, but the basic workflow with `ShellSession` works well (using python2 aexpect-worker, which needs to be adjusted before declaring aexpect fully python3 compatible)
=> Support for python3

aexpect/client.py
From time to time one needs to send ctrl+... characters to the
underlying process. One can either find and use the actual value, or
they can use this function, which does the mapping itself. To use it
simply specify the key to be pressed together with ctrl and you're set.
Note: Don't mistake this method with send_ctrl, which is used to send
control messages to the aexpect process and not to your underlying
process.
=> aexpect.client: Add support to sendcontrol characters

aexpect/client.py
If stream of a command (eg. nc connect to a remote socket) is not a using local code page, decode the stream with local code page in strict mode will raise exception like:
'''UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte'''.
Signed-off-by: Xu Tian <xutian@redhat.com>
=> aexpect.client: ignore error when decode

Makefile, aexpect.spec, python-aexpect.spec
This PR is a first step towards reducing the amount of differences between upstream and downstream packages.
The rationale is that these RPM packages are mostly (if not exclusively) developed and used on Fedora on EL, and by having similar packages, downstream can pick updates faster and make them quickly available to users.
This would also greatly help the packaing of projects such as Avocado, in which we currently have to deal with aexpect coming from either our custom repo (and package named `aexpect` or from downstream packages by the name of `python-aexpect`).
=> RPM packaging: upstream and downstream delta reduction

aexpect/client.py
When all received chars are ignored the reader assumes it's over. Let's
simply skip round and wait for really empty input.
=> client: Avoid early finish on ignored chars

aexpect/utils/path.py, scripts/aexpect-helper
This collection of fixes makes aexpect-helper work correctly on Python 3.
This was tested with Avocado's Docker runner plugin on a Python 3 environment.
=> Python 3: fix aexpect-helper

.travis.yml
This is the most basic way of making sure aexpect is Python 3 compatible.
Other types of testing should follow in the future though, and not
only for Python 3 (including unittests, functional tests and
integration tests).
=> Add (Travis) CI checks on Python 3

aexpect/client.py, python-aexpect.spec
These minor changes should allow both py2 and py3 specific versions of the aexpect helper to be built and installed at the same time without conflicting.
Is there anything external to this package that uses the `aexpect-helper` script?
Would it be OK to simplify this change further and skip having the client code fall back to finding an unversioned helper?
=> Update to install/use python version specific helper script

Makefile, python-aexpect.spec
Let's make upstream SPEC file more in sync with what's on Fedora/EPEL and Makefile similar to Avocado's.
---
Changes from v1 (#25):
* Removed the use of old chroot (new commit)
* Rebased on top of master, which includes the fixes on PR #23, making the Python 3 RPM work on its own
=> RPM Packaging: sync with Fedora/EPEL [v2]

aexpect/client.py, setup.py, tests/test_pass_fds.py
aexpect.client: To support fd passing
Add new argument `pass_fds` for `Spawn`/`Tail`/`Expect`/`ShellSession`
and their related wrappers to support fd passing.
In python 2, the above utilities do support (implicit) fd passing, but
these would not work in python 3 for some reasons. By applying this
patch, now users can pass fds to the target process explicitly, and
implicit fd passing is not allowed.
Signed-off-by: Xu Han xuhan@redhat.com
----
Changes:
```
v2:  replace subprocess with subprocess32
v3:  install denpendence via setup.py
```
=> To support fd passing [v3]

python-aexpect.spec
This adds the new requirements to RPM spec file. We still need to decide
whether to ask for "python-subprocess32" in EPEL or to skip the new
requirement and create a custom (simplified) backport as described in:
https://github.com/avocado-framework/aexpect/pull/32
but currently this builds well on Fedora.27
=> spec: Add new requirements for python2

aexpect/client.py
The first patch comes from https://github.com/avocado-framework/aexpect/pull/29 (unmodified, rebased) and the second one is my addition to allow to override the encoding.
=> Improve default encoding and allow to override it

setup.py
The "install_requires" can (at least on my python 2.7.5 with pip 10.0.1)
only be simple requires without python version dependency. Let's address
this programatically.
=> setup: Avoid using unsupported "install_requires" expression

.travis.yml, Makefile, aexpect/client.py, setup.py, tests/test_client.py
And the very minimum test infrastructure.  This should allow one
to run the tests by doing the classical:
$ python setup.py test
And of course can and will be extended/enabled on `make check`,
Travis-CI, etc.
---
Changes from v1 (#28):
* The test itself was completely rewritten (and simplified)
=> Tests: add a basic client/Spawn test [v2]

aexpect/client.py
Some type of shell (e.g. windows batch) would return a negative errno
on command failure, we should handle this, otherwise, would get a
`ShellStatusError`.
Signed-off-by: Xu Han <xuhan@redhat.com>
=> client: Fix shell status error

aexpect/client.py
When a system is under heavy load, calling `s.cmd_status_output()`
might get `ShellStatusError`, the problem is the command of
getting status may not finish in 10s (the current value).
The patch tries to solve the problem by enlarging the value to 30s.
Signed-off-by: Xu Han <xuhan@redhat.com>
=> client: Fix the issue of getting command status

Makefile, aexpect/client.py, aexpect/utils/path.py, requirements-travis.txt
The latest pylint version being installed by travis (2.0.1) is breaking due to:
https://github.com/PyCQA/pylint/issues/1318
Inspektor 0.5.2 has a pylint 2.0 compatibility commit:
https://github.com/avocado-framework/inspektor/commit/d72a157a0d59b42f456c46d07d8b21f7e0cab274
This PR updates the lint requirements to inspektor==0.5.2 and fixes issues reported by the new pylint version.
=> Update inspektor in travis to 0.5.2

aexpect/client.py
This patchset replaces select() with poll() so that we can avoid "ValueError: filedescriptor out of range in select()" when spawning several aexpect processes.
Tested via avocado with:
```
avocado run io-github-autotest-qemu.qmp_command.qmp_query-status \
--vt-type qemu --vt-arch ppc64le --vt-extra-params nettype=user
```
and
```
avocado run io-github-autotest-qemu.stress_boot \
--vt-type qemu --vt-arch ppc64le --vt-extra-params nettype=user max_vms=250
```
The above is an improvement from the previous state where the test would fail with max_vms = 60
This also introduces a change in behavior where tail threads are no longer allowed to start if the `close()` method has already been called, i.e. the child process is not running anymore and the readers have already been removed.
Closes #44
=> Use select.poll for waiting on file descriptors

aexpect/client.py
This patchset replaces select() with poll() so that we can avoid "ValueError: filedescriptor out of range in select()" when spawning several aexpect processes.
Tested via avocado with:
```
avocado run io-github-autotest-qemu.qmp_command.qmp_query-status \
--vt-type qemu --vt-arch ppc64le --vt-extra-params nettype=user
```
and
```
avocado run io-github-autotest-qemu.stress_boot \
--vt-type qemu --vt-arch ppc64le --vt-extra-params nettype=user max_vms=250
```
The above is an improvement from the previous state where the test would fail with max_vms = 60
This also introduces a change in behavior where tail threads are no longer allowed to start if the `close()` method has already been called, i.e. the child process is not running anymore and the readers have already been removed.
Closes #44 …
=> Use select.poll for waiting on file descriptors [v2]

aexpect/client.py
The safer cmd_output call disregards ExpectTimeoutError exceptions
and sends an extra new line to clear the shell prompt in case of
unwanted ouput which made it fail previously matching the same prompt.
Signed-off-by: Plamen Dimitrov <pdimitrov@pevogam.com>
=> Fix fallout from exception catch refactoring in fdff994efd

aexpect/remote_door.py, tests/test_remote_door.py
Add remote door utility to execute python code on remote locations
This utility supports a number of possibilities to execute code
remotely, among which:
1) Running control files
2) Using remote objects
3) Using decorators for remotely running functions
For more information, please consult the module docstring.
=> Remote utils extension door

aexpect/client.py
Sometimes the output might contain binary fragments, that are not
parsable to the system encoding. Let's use 'replace', resp
'backslashreplace' in get_output to allow such segments without
erroring-out. This should be fairly consistent as we do 'ignore'
most of the time.
=> Allow binary fragments in the output

aexpect/rss_client.py
The file `aexpect/rss_client.py` contains an unnecessary `#!/usr/bin/python` line that, when packaged, results in the following error when `rpmlint` is run:
```
python3-aexpect.noarch: E: non-executable-script /usr/lib/python3.9/site-packages/aexpect/rss_client.py 644 /usr/bin/python 
```
This PR simply removes that extraneous line to clean up the error.
=> Remove vestigial python shebang line from rss_client.py

.travis.yml, aexpect/client.py, aexpect/utils/process.py, scripts/aexpect_helper
In case the output produces non-decodable characters the `read_until_output_matches` can return earlier as it considers that a closed pipeline. Let's detect the closed pipeline by counting the raw bytes rather than decoded value with ignored values.
This is an alternative solution of the issue described in: https://github.com/avocado-framework/aexpect/pull/78
=> Make sure read_until_output_matches waits for all data

python-aexpect.spec
The Fedora `python-aexpect` package was recently brought back as a non-modular package. To un-retire the package, it underwent a fresh Fedora package review process which resulted in cleanup to the SPEC file. (See https://bugzilla.redhat.com/show_bug.cgi?id=1930954 for discussion.)
This PR brings the downstream package SPEC file cleanup to the upstream SPEC file.
=> Spec file cleanup resulting from downstream package review.

aexpect/client.py, aexpect/remote.py, aexpect/remote_door.py, aexpect/utils/wait.py
As Aexpect is a library used by other applications, it makes sense
to limits its logging and not log directly to the root logger.
=> Add logging namespace for all relevant aexpect modules

requirements-travis.txt
Newly release inspektor adds compatiblity with latest pylint versions
and fixes the current CI failure.
=> CI: bump Travis requirements for inspektor

aexpect/remote.py
In commit 23829fca09f75badf651acb593e7d4e4e2a98001, a new parameter
was introduced, but it broke the nc client. This patch fixes the
problem.
Signed-off-by: Xiaodai Wang <xiaodwan@redhat.com>
=> Fix remote_login with nc client for windows guest

aexpect/utils/astring.py
the bracketed-paste generates '\x1b[?2004l' and '\x1b[?2004h' console
codes that needs to be added to the list of console codes otherwise such
output breaks 'strip_console_codes'.
=> astring: Add bracketed paste console codes

Makefile, aexpect/remote_door.py
The previous approach of using a variable initialied only on given
condition after verifying the same condition seems to be all too
convoluted for linters so let's simplify it until they are happy.
=> Simpler ns daemon and current linter fixes

aexpect/remote_door.py
Using re.sub would result in some special characters like backslashes being processed despite us providing repr() of the metaprogramming embedded values. This is only a problem in some rare cases but as we want any code to be included in a remote control file as-is in its raw form, repr() is best utilized with a more standard string replace() call.
To further illustrate what is meant here:
>>> print("b = " + repr(p["tmp"]))
b = 'C:\\'
>>> print(re.sub(r"a = .*", "b = " + repr(p["tmp"]), "a = abc"))
b = 'C:\'
=> Drop unexpected and unwanted re.sub string postprocessing

aexpect/remote_door.py
In case the parameter is not found we need to return immediately, otherwise we'd be replacing everything with our parameter.
This was introduced in https://github.com/avocado-framework/aexpect/pull/101 and was the source of the selftest hangs.
=> Fix remote_door set_subcontrol_* handling of no matches

aexpect/ops.py
Add a small library of frequent operations performed in aexpect sessions.
v1: Initial pull request, later split into manageable parts.
v2: Main session ops module contribution and selection of reusable session functions, rebased on most recent aexpect tag.
=> Add session ops utility with some facilitator functions (v2)

aexpect/ops.py
This is especially useful for large files where calculating the hash can take long and even time out.
=> Allow to calculate hashes on parts of files

aexpect/client.py, aexpect/remote.py
In cases where one works with multiple (and many) remote hosts and sessions at the same time it is really useful to be able to see what remote host the command executed on.
=> Provide the session prefix when logging sent commands

aexpect/ops_linux.py
This was previously done via `ops.ls` but the `ls` would return a "serious error" exit code 2 when the expanded glob pattern results in zero paths. The current reimplementation makes use of `echo` to achieve the same with safe zero path outcome that won't hide more serious errors.
=> Add remote linux glob behavior to expand paths from patterns

aexpect/client.py
On two places we used to call _print_line even though self.output_func was not set, which resulted in warnings. It would be nicer to put this check directly to the _print_line function, but it is used inside performance critical section so let's check that directly on the corresponding places.
=> Avoid printing line when output_func not set

.github/workflows/ci.yml
We are having an issue with running the CI on py3.6 because the reference 3.6 cannot be found on the
github python versions manifest [1]. Let's stick to 3.x only.
[1] https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
=> .github/workflows/ci.yml: Fix CI on python 3.6

Makefile, python-aexpect.spec
I forgot to make that update when cutting 1.7.0.
=> python-aexpect.spec: Update spec with latest version

aexpect/remote.py
After RemoteSession initialization and before set_output_func, There are very short time intervals, but sometimes messages will be lost or printed via `print_line`. The solution is to define `set_output_func`/`set_output_params` when initializing RemoteSession because it natively supports them.
Signed-off-by: Yihuang Yu <yihyu@redhat.com>
=> remote_login: Fix problem of losing logs before setting output_func

aexpect/remote_door.py
Adjust remote door file transfer port in case of custom choices and shorten remote door's control file output to a readable length both of which are small tweaks to make the remote door slightly more flexible.
These changes also allow us to run avocado tests with a remote spawner and perform distributed testing.
=> Remote door tweaks

aexpect/ops_windows.py, requirements-travis.txt
the setuptools are no longer defaults and need to be stated explicitly.
=> requirements: Add setuptools

README.rst
let's add a very rough but practical usage guide to our README.
=> README: Add simple usage

aexpect/remote.py
`pipes` was deprecated since version 3.11 so let's replace the use of that module with the alternatives.
=> Drop the use of pipes

aexpect/ops_linux.py
This adds a new functionality to the ops_linux.py enabling greping on direct commands outputs.
=> Add grep_pipe

aexpect/client.py
When aexpect_helper does not work properly, the process will hang without any log information. This fix checks the process status and raises an error if the process terminates prematurely.
=> fix: Raise error when aexpect_helper doesn't work properly

Makefile
disable too-many-positional-arguments (R0917) in our CI as we don't intend to refactor the code to use named arguments instead.
=> Makefile: Skip newly added R0917

aexpect/remote_door.py, tests/test_remote_door.py
The main adaptation that was needed comes down to dropping the previous expose-free approach and dynamically exposing each relevant function and class in addition to the previous autoproxy steps.
To allow for modules and classes that the shared remote object has not explicitly imported or are not detectable as needing exposing, the previous whitelist argument has been extended to allow exposing predefined classes and serializing predefined exceptions that could be used and raised during remote use.
=> Provide Pyro5 compatibility to the remote door utility

aexpect/remote_door.py, tests/test_remote_door.py
This is a more rarely used case that we could cover with Pyro5 support as well. The advertised method remains in retrieving multiple remote objects one by one using single remote object getter and this one remains more manual and requiring of control file implementation.
=> Provide remote Pyro5 compatibility for multiple remote objects

aexpect/client.py
The output coming from the console Terminal consists of Bracketed Paste escape sequence! I have updated the code in a way that it will check the status output and see if the output has this sequence, it will remove this from the output and then use only integer o/p of status command!
Before applying the patch status output was:
^[[?2004l0
After applying the patch status output is:
0
Signed-off-by: Anushree Mathur [anushree.mathur@linux.vnet.ibm.com](mailto:anushree.mathur@linux.vnet.ibm.com)
=> Removing the escape sequence from the console output!

aexpect/remote.py, tests/test_remote.py
This commit adds support for a new rsync client for remote copy operations which is especially important now that the SCP protocol is being deprecated.
=> Add rsync client for remote copy operations

aexpect/client.py
In console outputs we are getting escape sequences because of which most of the testcases are failing to use the output of few commands. This PR removes the escape sequence first then use the output.This PR fixes multiple testcases.
Signed-off-by: Anushree Mathur <anushree.mathur@linux.vnet.ibm.com>
=> Removing escape sequence from output in cmd_output function!

Makefile, aexpect/client.py, aexpect/exceptions.py, aexpect/ops_linux.py, aexpect/ops_windows.py, aexpect/remote.py, aexpect/remote_door.py, aexpect/rss_client.py, aexpect/shared.py, aexpect/utils/astring.py, aexpect/utils/data_factory.py, aexpect/utils/path.py, aexpect/utils/process.py, requirements-travis.txt, setup.py, tests/test_client.py, tests/test_pass_fds.py, tests/test_remote.py, tests/test_remote_door.py, tests/test_utils.py
This PR is built on top of #151 and adds python black style fixes.
=> Enable black formatter

aexpect/client.py, aexpect/remote.py, aexpect/rss_client.py, aexpect/shared.py, aexpect/utils/wait.py
@smitterl identified a bug in aexpect, when unkillable `aexpect_worker` results in indefinite hang of `Spawn.close()`. To mitigate that I added a timeout to our `wait_for_lock` and used it in `close()` (this fix can be tested by commenting-out the `kill`). Then I noticed the `close()` can actually be called multiple times when the user uses multiple processes/threads. To address that I'd suggest moving to BSD flock rather than posix lockf as that one protects individual threads and adding another `close` lock file to protect this critical path. This can be tested by:
```
import aexpect
import threading
#import pydevd
def close_session(session):
"""Closes the given session."""
#pydevd.settrace("127.0.0.1")
session.close()
session = aexpect.ShellSession("bash")
threads = []
for _ in …
```
=> Failed kill

Makefile, python-aexpect.spec, setup.py
=> aexpect: Version 1.8.0

README.rst, aexpect/client.py
Few docs changes inspired by https://github.com/avocado-framework/aexpect/issues/154
=> Docs improvements
